#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f "config/Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew update
  brew tap homebrew/bundle 2>/dev/null

  brew bundle check 2>&1 >/dev/null || {
    echo "==> Installing Homebrew dependencies..."
    brew bundle
  }
fi

echo "==> Installing node modules..."
npm install
