#!/bin/sh

# script/seedwatson: Seeds Watson with scraped pill images

set -e

cd "$(dirname "$0")/.."

echo "==> Scraping drugs.com for drug images..."
rake

echo "==> Sending images to Watson"
node ./watsonUpload

echo "==> Done!"
