#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

if psql -lqt | cut -d \| -f 1 | grep -w crowd_health_development; then
  echo "Database already exists"
  echo "==> Removing previous database..."

  # remove surrounding whitespace
  dropdb "$(psql -lqt | cut -d \| -f 1 | grep -w crowd_health_development | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
fi

echo "==> Setting up DB..."
createdb crowd_health_development
npm run migrate:latest

echo "==> App is now ready to go!"
